USE test
GO



CREATE TABLE BOOK_CHECKOUTS
(
	PERSON_ID INT,
	ISBN CHAR(14),
	DUE_DATE DATE,
	CONSTRAINT BOOK_CHECKOUTS_PK PRIMARY KEY (PERSON_ID, ISBN, DUE_DATE),
	CONSTRAINT BOOK_CHECKOUTS_ISBN_FK FOREIGN KEY (ISBN) REFERENCES LIBRARY_BOOKS (ISBN),
	CONSTRAINT BOOK_CHECKOUTS_PERSON_ID_FK FOREIGN KEY (PERSON_ID) REFERENCES LIBRARY_CUSTOMERS (PERSON_ID)
);


SELECT * FROM BOOK_CHECKOUTS_REPORT;
SELECT * FROM LIBRARY_BOOKS;

INSERT INTO BOOK_CHECKOUTS
SELECT PERSON_ID, LB.ISBN, DUE_DATE
FROM (
		SELECT	PERSON_ID,
				BOOK_TITLE1 AS BOOK_TITLE,
				BOOK1_DUE_DATE AS DUE_DATE
		FROM BOOK_CHECKOUTS_REPORT bcr
		UNION
		SELECT	PERSON_ID,
				BOOK_TITLE2 AS BOOK_TITLE,
				BOOK2_DUE_DATE AS DUE_DATE
		FROM BOOK_CHECKOUTS_REPORT bcr
		WHERE BOOK_TITLE2 IS NOT NULL
) AS S
LEFT JOIN LIBRARY_BOOKS LB ON S.BOOK_TITLE = LB.BOOK_TITLE
;


SELECT * FROM BOOK_CHECKOUTS;
