CREATE DATABASE SchoolManagementDb222
GO

USE SchoolManagementDb222

CREATE TABLE Students(
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	DateOfBirth DATE,
	StudentId NVARCHAR(10) UNIQUE,
	ProgrammeOfStudy NVARCHAR(150) NOT NULL,
);

CREATE TABLE Lecturers(
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	DateOfBirth DATE,
	StaffId NVARCHAR(10) UNIQUE,
);

-- DROP TABLE Lecturers

CREATE TABLE Courses(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(50) NOT NULL,
	Code NVARCHAR(5) UNIQUE,
	Credits INT,
);

-- USE master
-- DROP DATABASE SchoolManagementDb222;